src/main/resources/wa-task-completion-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-configuration-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-initiation-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-permissions-fpl-CARE_SUPERVISION_EPO.dmn

Updating DMNs for latest changes for send/reply to message tasks
```
[ ] Yes
[x ] No
```

Updating DMNs with send/reply to message events

---

src/main/resources/wa-task-completion-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-configuration-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-initiation-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-permissions-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-types-fpl-CARE_SUPERVISION_EPO.dmn

Update DMNs to latest

---

src/main/resources/wa-task-completion-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-configuration-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-initiation-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-permissions-fpl-CARE_SUPERVISION_EPO.dmn
src/main/resources/wa-task-types-fpl-CARE_SUPERVISION_EPO.dmn

https://tools.hmcts.net/jira/browse/DFPL-1177
Add descriptions/links for all tasks
```
[ ] Yes
[X] No
```

Update DMNs with descriptions

---

build.gradle

Update SonarQube config

---

src/main/resources/wa-task-types-publiclaw-care_supervision_epo.dmn

Update task-types XML things

---

src/main/resources/wa-task-cancellation-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaCancellationTest.java

Update cancellation DMN with proper field names

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn
src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaPermissionsTest.java

Change to collect hit policy

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn

Add null checks for region info

---

src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn

Changing hmcts-ctsc role to ctsc
```
[ ] Yes
[ x] No
```

Changing hmcts-ctsc role to ctsc

---

src/main/resources/wa-task-initiation-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaInitiationTest.java

https://tools.hmcts.net/jira/browse/DFPL-1515
- Update params for submitApplication
```
[ ] Yes
[X] No
```

DFPL-1515: Update publish params

---

src/main/resources/fpl-specific-holidays.json

Update court specific calendar test date to 9 June
```
[ ] Yes
[ x] No
```

Update test court specific holiday to 9 June

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn
src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaConfigurationTest.java

- Update task prioritisations
- Cast due date time to a string
```
[ ] Yes
[X] No
```

Update task prioritisation + urgentApplication dueDateTime

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn
src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn

https://tools.hmcts.net/jira/browse/DFPL-1553
- Use substrings to force a parseable time, rather than rely on camunda's casting...
- Update the Next Steps/Description for the review<x>Application tasks to explicitly spell out that adding a case number has to be done first!
```
[ ] Yes
[X] No
```

reviewUrgentApplication substrings + update wording of next steps

---

config/owasp/suppressions.xml
src/main/resources/wa-task-cancellation-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaCancellationTest.java

N/A
- Add missing changeCaseName-superuser to cancellation/reconfigure config
```
[ ] Yes
[X] No
```

Add superuser version of changeCaseName to Reconfiguration config

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaConfigurationTest.java

N/A
- Add description for specific access tasks
```
[ ] Yes
[X] No
```

Add next steps for specific access tasks

---

config/owasp/suppressions.xml
src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn

N/A
- Make sure that allocated/hearing judge permissions are last in the DMN, so they aren't overridden
```
[ ] Yes
[X] No
```

Rearrange order so that auto assigning is LAST

---

src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn

https://tools.hmcts.net/jira/browse/COT-413
- Remove authorisation code from auto assigning permissions
```
[ ] Yes
[ X] No
```

Remove authorisation code from case-role auto assigning tasks

---

config/owasp/suppressions.xml
src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn
src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaConfigurationTest.java
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaPermissionsTest.java

DFPL-1561 
- Stage DMNs in demo
```
[ ] Yes
[X] No
```

DFPL-1561 (Demo)

---

.github/renovate.json
config/owasp/suppressions.xml
src/main/resources/wa-task-completion-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaCompletionTest.java

Fix task completion

---

.github/renovate.json
config/owasp/suppressions.xml
src/main/resources/wa-task-completion-publiclaw-care_supervision_epo.dmn
src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn
src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaCompletionTest.java
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaConfigurationTest.java
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaPermissionsTest.java

https://tools.hmcts.net/jira/browse/DFPL-1618
- Take currently staged demo DMNs and deploy to PROD/AAT
```
[ ] Yes
[X] No
```

DFPL-1618: Update master with demo DMNs ready for release

---

src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaPermissionsTest.java

[DEMO] Grant everyone read access to all tasks

---

src/main/resources/wa-task-initiation-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaInitiationTest.java

N/A
- Re-enable the task initiation in demo for testing
```
[ ] Yes
[X] No
```

Re-enable task initiation

---

src/main/resources/wa-task-initiation-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaInitiationTest.java

- Renable demo initiation DMNs
```
[ ] Yes
[X] No
```

Re enable task initiation (demo)

---

Jenkinsfile_CNP

N/A
- Disable syncing demo DMNs with prod whilst we're in evaluation period
```
[ ] Yes
[X] No
```

Disable demo sync

---

src/main/resources/wa-task-initiation-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaInitiationTest.java

Re enable task initiation

---

Jenkinsfile_CNP
build.gradle
src/main/resources/wa-task-cancellation-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaCancellationTest.java

Stage Dfpl 2031 in DEMO

---

src/main/resources/wa-task-initiation-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaInitiationTest.java

https://tools.hmcts.net/jira/browse/DFPL-2108
Fix high court task initiation after accidental removal due to merge conflicts
```
[ ] Yes
[X] No
```

DFPL-2108-Demo-2: Fix High court task initiation in demo

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn

N/A
- Add null checking around the taskAttributes.roleAssignmentId like in demo
```
[ ] Yes
[X] No
```

Use NPE safe roleAssignmentId value

---

src/main/resources/wa-task-initiation-publiclaw-care_supervision_epo.dmn

https://tools.hmcts.net/jira/browse/DFPL-2108
Alter court code
```
[ ] Yes
[X] No
```

DFPL-2108-Demo: Alter Court code to check for string

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaConfigurationTest.java

https://tools.hmcts.net/jira/browse/DFPL-2109
Add the date/time of task creation to task names
```
[ ] Yes
[X] No
```

DFPL-2109 Add the date/time of task creation to task names

---

src/main/resources/wa-task-cancellation-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaCancellationTest.java

Update cancellation DMN to cancel tasks on migrateCase

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaConfigurationTest.java

[DFPL-2471](https://tools.hmcts.net/jira/browse/DFPL-2471)
- Make sure review message/response has role category that reflects the hearing/allocated judge/legal adviser on the case
```
[ ] Yes
[X] No
```

DFPL-2471: Message allocated/hearing judge tasks conditional roleCategory

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn

https://tools.hmcts.net/jira/browse/DFPL-2523
- Update next steps for the "View additional applications" task to signpost Judicial users to the right events before completing the task.
```
[ ] Yes
[X] No
```

DFPL-2523: Update the description/next steps for View additional applications

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn

https://tools.hmcts.net/jira/browse/DFPL-2108
Fix typo in reviewOrderCMOHighCourt name
```
[ ] Yes
[X] No
```

DFPL-2108-Fix: Fix typo in task type name HighCourt

---

src/main/java/uk/gov/hmcts/reform/fpl/dmn/FplTask.java
src/main/resources/wa-task-completion-publiclaw-care_supervision_epo.dmn
src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn
src/main/resources/wa-task-initiation-publiclaw-care_supervision_epo.dmn
src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaCompletionTest.java
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaConfigurationTest.java
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaInitiationTest.java

[DFPL-2537](https://tools.hmcts.net/jira/browse/DFPL-2537)
- Add listing event task for court admins
```
[ ] Yes
[X] No
```

DFPL-2537: Add DMN configuration for reviewListingAction task

---

src/main/resources/wa-task-types-publiclaw-care_supervision_epo.dmn

TBC
- Add missing task type to the filter on All Work
```
[ ] Yes
[X] No
```

Add missing listing task type to filter

---

src/main/resources/wa-task-initiation-publiclaw-care_supervision_epo.dmn

https://tools.hmcts.net/jira/browse/DFPL-2304
DFPL-2304 c110a Design changes to hearing urgency section
Update DMN table with the new hearing urgency field
```
[ ] Yes
[X] No
```

 DFPL-2304 c110a Design changes to hearing urgency section

---

src/main/resources/wa-task-permissions-publiclaw-care_supervision_epo.dmn
src/test/java/uk/gov/hmcts/reform/fpl/dmn/CamundaTaskWaPermissionsTest.java

DFPL-2669
- Revert removing the manual completion button for judicial tasks
```
[ ] Yes
[X] No
```

Revert "DFPL-2669: Disable manual completion for judicial/local court tasks (#289)"

---

src/main/resources/wa-task-configuration-publiclaw-care_supervision_epo.dmn

DFPL-2726
- Add date to the end of the correspondence task title
```
[ ] Yes
[X] No
```

DFPL-2726: Add date to correspondence task title
